//  CuteBubbles —— 每张气泡量出来的点九数据
//  生成自 tools/measure.py，改素材要重新量。

import SwiftUI

// MARK: - 全部 21 张

public extension BubbleSkin {
    /// 量好的全套气泡。id 跟 Assets/png 里的文件名一一对应。
    static let all: [BubbleSkin] = [
        .init(id: "halo-gray", name: "光环灰", asset: "BubbleSkin-halo-gray",
              cap: .init(top: 31.3, leading: 50.3, bottom: 25.7, trailing: 51.0),
              pad: .init(top: 19.0, leading: 22.0, bottom: 14.7, trailing: 22.7)),
        .init(id: "comic", name: "漫画框", asset: "BubbleSkin-comic",
              cap: .init(top: 25.7, leading: 39.0, bottom: 31.3, trailing: 40.0),
              pad: .init(top: 14.0, leading: 18.0, bottom: 21.7, trailing: 19.0)),
        .init(id: "pixel-cat", name: "像素猫", asset: "BubbleSkin-pixel-cat",
              cap: .init(top: 32.0, leading: 45.2, bottom: 25.0, trailing: 51.5),
              pad: .init(top: 17.7, leading: 22.0, bottom: 17.3, trailing: 28.3)),
        .init(id: "pink-cat", name: "粉猫", asset: "BubbleSkin-pink-cat",
              cap: .init(top: 33.3, leading: 60.5, bottom: 23.7, trailing: 47.1),
              pad: .init(top: 21.0, leading: 38.7, bottom: 16.0, trailing: 25.3)),
        .init(id: "cloud", name: "云朵", asset: "BubbleSkin-cloud",
              cap: .init(top: 35.3, leading: 49.7, bottom: 21.7, trailing: 51.1),
              pad: .init(top: 22.0, leading: 26.3, bottom: 15.0, trailing: 27.7)),
        .init(id: "halo-blue", name: "光环蓝", asset: "BubbleSkin-halo-blue",
              cap: .init(top: 33.3, leading: 52.4, bottom: 23.7, trailing: 50.7),
              pad: .init(top: 15.3, leading: 23.7, bottom: 14.7, trailing: 22.0)),
        .init(id: "rain", name: "下雨", asset: "BubbleSkin-rain",
              cap: .init(top: 33.3, leading: 51.1, bottom: 23.7, trailing: 55.8),
              pad: .init(top: 20.0, leading: 30.3, bottom: 15.7, trailing: 35.0)),
        .init(id: "halo-silver", name: "光环银", asset: "BubbleSkin-halo-silver",
              cap: .init(top: 33.0, leading: 50.6, bottom: 24.0, trailing: 50.6),
              pad: .init(top: 15.0, leading: 22.3, bottom: 15.3, trailing: 22.3)),
        .init(id: "music", name: "音符", asset: "BubbleSkin-music",
              cap: .init(top: 26.7, leading: 58.0, bottom: 30.3, trailing: 49.7),
              pad: .init(top: 12.3, leading: 27.3, bottom: 18.3, trailing: 19.0)),
        .init(id: "halo-pink", name: "光环粉", asset: "BubbleSkin-halo-pink",
              cap: .init(top: 32.0, leading: 50.3, bottom: 25.0, trailing: 51.0),
              pad: .init(top: 14.3, leading: 22.3, bottom: 17.0, trailing: 23.0)),
        .init(id: "nurse", name: "护士", asset: "BubbleSkin-nurse",
              cap: .init(top: 29.3, leading: 42.1, bottom: 27.7, trailing: 51.4),
              pad: .init(top: 15.3, leading: 19.7, bottom: 15.3, trailing: 29.0)),
        .init(id: "rain-bear", name: "雨熊", asset: "BubbleSkin-rain-bear",
              cap: .init(top: 31.0, leading: 56.2, bottom: 26.0, trailing: 58.6),
              pad: .init(top: 10.0, leading: 27.3, bottom: 13.0, trailing: 29.7)),
        .init(id: "sailor", name: "水手", asset: "BubbleSkin-sailor",
              cap: .init(top: 27.0, leading: 55.2, bottom: 30.0, trailing: 52.8),
              pad: .init(top: 11.3, leading: 32.7, bottom: 11.3, trailing: 30.3)),
        .init(id: "fish", name: "小鱼", asset: "BubbleSkin-fish",
              cap: .init(top: 24.7, leading: 39.4, bottom: 32.3, trailing: 39.4),
              pad: .init(top: 13.3, leading: 20.3, bottom: 24.0, trailing: 20.3)),
        .init(id: "bow-cat", name: "结猫", asset: "BubbleSkin-bow-cat",
              cap: .init(top: 29.7, leading: 47.9, bottom: 27.3, trailing: 53.9),
              pad: .init(top: 17.7, leading: 28.0, bottom: 21.7, trailing: 34.0)),
        .init(id: "moon-bunny", name: "月亮", asset: "BubbleSkin-moon-bunny",
              cap: .init(top: 16.7, leading: 52.1, bottom: 40.3, trailing: 47.1),
              pad: .init(top: 15.7, leading: 34.3, bottom: 26.0, trailing: 29.3)),
        .init(id: "snow", name: "雪天", asset: "BubbleSkin-snow",
              cap: .init(top: 34.7, leading: 49.8, bottom: 22.3, trailing: 52.8),
              pad: .init(top: 22.7, leading: 26.3, bottom: 12.0, trailing: 29.3)),
        .init(id: "peek-cat", name: "趴猫", asset: "BubbleSkin-peek-cat",
              cap: .init(top: 32.3, leading: 48.3, bottom: 24.7, trailing: 55.6),
              pad: .init(top: 20.0, leading: 22.7, bottom: 9.0, trailing: 30.0)),
        .init(id: "paw", name: "肉垫", asset: "BubbleSkin-paw",
              cap: .init(top: 29.3, leading: 40.8, bottom: 27.7, trailing: 53.1),
              pad: .init(top: 18.0, leading: 17.7, bottom: 19.3, trailing: 30.0)),
        .init(id: "bird", name: "小鸟", asset: "BubbleSkin-bird",
              cap: .init(top: 20.0, leading: 41.9, bottom: 37.0, trailing: 40.6),
              pad: .init(top: 9.0, leading: 23.3, bottom: 20.3, trailing: 22.0)),
        .init(id: "bandaid", name: "创可贴", asset: "BubbleSkin-bandaid",
              cap: .init(top: 30.7, leading: 56.4, bottom: 26.3, trailing: 44.4),
              pad: .init(top: 14.0, leading: 34.3, bottom: 10.3, trailing: 22.3)),
    ]
}
